config/routes.rb
CtoToolbox::Application.routes.draw do

  resources :toolboxes

  root :to => "static_pages#home"

  get "static_pages/home"

  get "user/list"
  get "user/disable"

  match 'users/:id/set_current_user' => 'users#set_current_user', :as => 'user_set_current_user', :via => "get"
  match 'tools/tag/:tag_name' => 'tools#filter_by_tag', :as => 'tool_filter_by_tag', :via => "get"
  match 'tools/:id/favorites' => 'tools#add_to_favorites', :as => 'tool_add_to_favorites', :via => "get" #TODO: change to post, and possibly change for this to be off /users endpoint
  match 'tools/:id/favorites' => 'tools#remove_from_favorites', :as => 'tool_remove_from_favorites', :via => "delete" #TODO: change to post, and possibly change for this to be off /users endpoint

  match "/auth/twitter/callback" => "sessions#create"

  
  resources :users
  resources :tags

  resources :tools
  resources :toolboxes
  match 'tools_search' => 'Tools#search_by_name', :as => :tools_search_by_name, :via => "get"
  match 'mytools' => 'Tools#my_tools', :as => :my_tools, :via => "get"

  

end

app/models/tool.rb
class Tool < ActiveRecord::Base

  #markable_as :toolbox, :by => :user
  acts_as_taggable
  #acts_as_taggable_on :tags
  has_and_belongs_to_many :users
  has_and_belongs_to_many :toolbox

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all

    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tools }
    end
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    @tool = Tool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tool }
    end
  end

  def search_by_name
    @tools = Tool.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @tools.map(&:name)
  end


  # GET /tools/new
  # GET /tools/new.json
  def new
    @tool = Tool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tool }
    end
  end

  # GET /tools/1/edit
  def edit
    @tool = Tool.find(params[:id])
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(params[:tool])

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render json: @tool, status: :created, location: @tool }
      else
        format.html { render action: "new" }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tools/1
  # PUT /tools/1.json
  def update
    @tool = Tool.find(params[:id])

    respond_to do |format|
      if @tool.update_attributes(params[:tool])
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to tools_url }
      format.json { head :ok }
    end
  end

  def add_to_favorites
    logger.warn "param #{params}, session #{session}"
    @tool = Tool.find(params[:id])
    @user = User.find(session[:current_user])

    if session[:current_toolbox]
        @current_toolbox = Toolbox.find(session[:current_toolbox])
        if !@current_toolbox.tools.include? @tool
           @current_toolbox.tools <<@tool 
           @current_toolbox.save
        end
    end

    
 
    #logger.info "user #{@user}, tool #{@tool}, toolbo_tools: #{@user.toolbox_tools}"
    #@user.set_mark :toolbox, @tool
    if !@user.tools.include? (@tool)
        @user.tools << @tool 
    end
    @user.save

    flash[:notice] = "Added Tool #{@tool.name} to #{@user.name}'s toolbox"

    @tools = Tool.all
    render 'index'
  end

def remove_from_favorites
    logger.warn "param #{params}, session #{session}"
    flash[:notice] = "Removing Tools not implemented yet" 
    @tools = Tool.all
    render 'index'
 end




#  def add_to_interested
#    @tool = Tool.find(params[:id])
#    @user = User.find(session[:current_user])
#    logger.info "BASSAFDASDFASF, user #{@user}, tool #{@tool}"
#    @user.interested_tools << @tool  
#    render 'index'
#  end


  def filter_by_tag
    @tools = Tool.tagged_with(params[:tag_name])
    render 'index'
    #match 'tools/tag/:tag_name' => 'tools#filter_by_tag', :as => 'tool_filter_by_tag', :via => "get"
  end


  def my_tools
    @user = User.find(session[:current_user])
    @tools = @user.tools 
    flash[:notice] = "Showing #{@user.name}'s ToolBox"
    render 'index'
  end


end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>


  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, data: { autocomplete_source: tools_search_by_name_path } %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows:5, cols:160 %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :public %>
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing Tool / Library / Framework</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<h1>Tools</h1>

<center>
<% if params[:tag_name] %>
    <div class='tags'>
       Filtered By <a class="label label-info tag" ><%= params[:tag_name] %> </a> &nbsp;
       Back To <%= link_to 'All Tools', tools_path, class:'label label-info tag' %>

    </div> <!--tags-->
    
<% end %>
</center>


<%= link_to 'New Tool', new_tool_path %>
  <% @tools.each do |tool| %>
   <hr>
<div class='bit '>
<div class=''>

<!--
<div class='span8 row header'>
  <div class='vote-box'> <i bit_id='306' class='icon-arrow-up upvote'></i> <div class='vote-count'>3</div> <i bit_id='306' class='icon-arrow-down downvote'></i>
</div>
-->

 <div class='title'>
 <%= link_to tool.name, tool %> (<%= link_to 'Edit', edit_tool_path(tool) %>)  
 
 <%= link_to "Add To My Toolbox", tool_add_to_favorites_path(tool.id), :class => 'add_label' %>


    <div class='tags'>
      <% tool.tag_list.each do |tag| %>
          <%= link_to tag, tool_filter_by_tag_path(tag), :class => 'label label-info tag' %> 


      <% end %>
    </div> <!--tags-->
 </div> <!--title-->
 </div> <!--row-->
</div> <!--bit row-->

<div class='row'>
<div class='span12 code'>
   <pre class='prettyprint'> Description: <%= tool.description %> </pre>
</div>
</div>

<!--
  <tr>
    <td><%= tool.category %></td>
    <td><%= tool.public %></td>
    <td><%= tool.url %></td>
    <td><%= tool.cost %></td>
    <td><%= link_to 'Show', tool %></td>
    <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
    <td><%= link_to 'Destroy', tool, confirm: 'Are you sure?', method: :delete %></td>
</tr>
-->
<% end %>
<!--
</table>
--%>

<br />

app/views/tools/new.html.erb
<h1>New Tool / Library / Framework</h1>

<%= render 'form' %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tool.name %>
</p>

<p>
  <b>Description:</b>
  <%= @tool.description %>
</p>

<p>
  <b>Category:</b>
  <%= @tool.category %>
</p>

<p>
  <b>Public:</b>
  <%= @tool.public %>
</p>

<p>
  <b>Url:</b>
  <%= @tool.url %>
</p>

<p>
  <b>Cost:</b>
  <%= @tool.cost %>
</p>


<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>