config/routes.rb
CtoToolbox::Application.routes.draw do

  resources :toolboxes

  root :to => "static_pages#home"

  get "static_pages/home"

  get "user/list"
  get "user/disable"

  match 'users/:id/set_current_user' => 'users#set_current_user', :as => 'user_set_current_user', :via => "get"
  match 'tools/tag/:tag_name' => 'tools#filter_by_tag', :as => 'tool_filter_by_tag', :via => "get"
  match 'tools/:id/favorites' => 'tools#add_to_favorites', :as => 'tool_add_to_favorites', :via => "get" #TODO: change to post, and possibly change for this to be off /users endpoint
  match 'tools/:id/favorites' => 'tools#remove_from_favorites', :as => 'tool_remove_from_favorites', :via => "delete" #TODO: change to post, and possibly change for this to be off /users endpoint

  match "/auth/twitter/callback" => "sessions#create"

  
  resources :users
  resources :tags

  resources :tools
  resources :toolboxes
  match 'tools_search' => 'Tools#search_by_name', :as => :tools_search_by_name, :via => "get"
  match 'mytools' => 'Tools#my_tools', :as => :my_tools, :via => "get"

  

end

app/models/user.rb
class User < ActiveRecord::Base
   #acts_as_marker
   has_and_belongs_to_many :tools
   has_and_belongs_to_many :toolboxes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def list
  end

  def set_current_user
    @user = User.find(params[:id])
    if @user 
       session[:current_user] = @user.id
       puts "Setting user #{@user}"
       puts "Setting user #{@user}"
       puts "Setting user #{@user}"
       flash[:notice] = "Set user #{@user.name} as current" 
       redirect_to(users_path)
    else


       flash[:notice] = "Did not find the user with id #{params[:id]}"
       redirect_to(users_path)
    end
  end

  def show
    @user = User.find(params[:id])
  end



  def disable
  end

  def favorites
  end

  def tolearn
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/disable.html.erb
<h1>User#disable</h1>
<p>Find me in app/views/user/disable.html.erb</p>

app/views/users/favorites.html.erb
<h1>User#favorites</h1>
<p>Find me in app/views/user/favorites.html.erb</p>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table">
  <thead>
    <th>Name</th>
      <!--
    <th>Provider</th>
    <th>UID</th>
    -->
  </thead>

<% @users.each do |user| %>
  <tr>
      <td><%= link_to user.name, user_path(user) 
          %></td>
      <!--
    <td><%= user.provider %></td>
    <td><%= user.uid %></td>
    -->
    
    <td>(<%= link_to "Set as current", user_set_current_user_path(user)%>)</td>
  </tr>
<% end %>
  <tfoot>
  </tfoot>
</table>

<br />

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%= @user.name %>
  </p>

<p>
  <b>ToolBoxes / Stacks:</b>
  <% if @user.toolboxes.exists? %>
      <% @user.toolboxes.each do |toolbox| %>
          <%= link_to toolbox.name, toolbox_path(toolbox) %> <br/> 
      <% end %>
<% else %>
      No ToolBoxes Defined Yet

  <% end %>
</p>



<p>
  <b>Tools:</b>
  <% if @user.tools.exists? %>
      <% @user.tools.each do |tool| %>
   <hr>
<div class='bit '>
<div class=''>

 <div class='title'>
    <%= link_to tool.name, tool %> <div class='tags'>
      <% tool.tag_list.each do |tag| %>
          <%= link_to tag, tool_filter_by_tag_path(tag), :class => 'label label-info tag' %> 
      <% end %>
    </div> <!--tags-->
 </div> <!--title-->
 </div> <!--row-->
</div> <!--bit row-->


<% end %>
<% else %>
      No Tools Defined Yet
  <% end %>



</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'All Users', users_path %>

app/views/users/tolearn.html.erb
<h1>User#tolearn</h1>
<p>Find me in app/views/user/tolearn.html.erb</p>