config/routes.rb
CtoToolbox::Application.routes.draw do

  resources :toolboxes

  root :to => "static_pages#home"

  get "static_pages/home"

  get "user/list"
  get "user/disable"

  match 'users/:id/set_current_user' => 'users#set_current_user', :as => 'user_set_current_user', :via => "get"
  match 'tools/tag/:tag_name' => 'tools#filter_by_tag', :as => 'tool_filter_by_tag', :via => "get"
  match 'tools/:id/favorites' => 'tools#add_to_favorites', :as => 'tool_add_to_favorites', :via => "get" #TODO: change to post, and possibly change for this to be off /users endpoint
  match 'tools/:id/favorites' => 'tools#remove_from_favorites', :as => 'tool_remove_from_favorites', :via => "delete" #TODO: change to post, and possibly change for this to be off /users endpoint

  match "/auth/twitter/callback" => "sessions#create"

  
  resources :users
  resources :tags

  resources :tools
  resources :toolboxes
  match 'tools_search' => 'Tools#search_by_name', :as => :tools_search_by_name, :via => "get"
  match 'mytools' => 'Tools#my_tools', :as => :my_tools, :via => "get"

  

end

app/models/toolbox.rb
class Toolbox < ActiveRecord::Base
     has_and_belongs_to_many :users 
     has_and_belongs_to_many :tools 
end

app/controllers/toolboxes_controller.rb
class ToolboxesController < ApplicationController
  # GET /toolboxes
  # GET /toolboxes.json
  def index
    @toolboxes = Toolbox.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @toolboxes }
    end
  end

  # GET /toolboxes/1
  # GET /toolboxes/1.json
  def show
    @toolbox = Toolbox.find(params[:id])

    session[:current_toolbox] = @toolbox.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @toolbox }
    end
  end

  # GET /toolboxes/new
  # GET /toolboxes/new.json
  def new
    @toolbox = Toolbox.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @toolbox }
    end
  end

  # GET /toolboxes/1/edit
  def edit
    @toolbox = Toolbox.find(params[:id])
  end

  # POST /toolboxes
  # POST /toolboxes.json
  def create
    @toolbox = Toolbox.new(params[:toolbox])
    @user = User.find(session[:current_user])
    @user.toolboxes << @toolbox
    @user.save
    @toolbox.users << @user

    respond_to do |format|
      if @toolbox.save
        format.html { redirect_to @toolbox, notice: 'Toolbox was successfully created.' }
        format.json { render json: @toolbox, status: :created, location: @toolbox }
      else
        format.html { render action: "new" }
        format.json { render json: @toolbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /toolboxes/1
  # PUT /toolboxes/1.json
  def update
    @toolbox = Toolbox.find(params[:id])

    respond_to do |format|
      if @toolbox.update_attributes(params[:toolbox])
        format.html { redirect_to @toolbox, notice: 'Toolbox was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @toolbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toolboxes/1
  # DELETE /toolboxes/1.json
  def destroy
    @toolbox = Toolbox.find(params[:id])
    @toolbox.destroy

    respond_to do |format|
      format.html { redirect_to toolboxes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/toolboxes_helper.rb
module ToolboxesHelper
end

app/views/toolboxes/_form.html.erb
<%= form_for(@toolbox) do |f| %>
  <% if @toolbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toolbox.errors.count, "error") %> prohibited this toolbox from being saved:</h2>

      <ul>
      <% @toolbox.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type, options_for_select([ "Product", "Project" ], "Project") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toolboxes/edit.html.erb
<h1>Editing toolbox</h1>

<%= render 'form' %>

<%= link_to 'Show', @toolbox %> |
<%= link_to 'Back', toolboxes_path %>

app/views/toolboxes/index.html.erb
<h1>Listing Toolboxes</h1>

<table class="table">
  <thead>
    <th>Name</th>
    <th>Url</th>
    <th>Owner(s)</th>
    <th></th>
    <th></th>
    <!--<th></th>-->
  </thead>

<% @toolboxes.each do |toolbox| %>
  <tr>
    <td><%= toolbox.name %></td>
    <td><%= toolbox.url %></td>
    <td><%= toolbox.users.collect{ |user| user.name}.join(' ,') %></td>

    <td><%= link_to 'Show', toolbox %></td>
    <td><%= link_to 'Edit', edit_toolbox_path(toolbox) %></td>
    <!--<td><%= link_to 'Destroy', toolbox, confirm: 'Are you sure?', method: :delete %></td>-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Toolbox', new_toolbox_path %>

app/views/toolboxes/new.html.erb
<h1>New toolbox</h1>

<%= render 'form' %>

<%= link_to 'Back', toolboxes_path %>

app/views/toolboxes/show.html.erb
<h2> ToolBox <%= @toolbox.name %> </h2>

<!--
<p>
  <b>Name:</b>
  <%= @toolbox.name %>
</p>
-->

<p>
  <b>Description:</b>
  <%= @toolbox.description %>
  </p>

<p>
  <b>Url:</b>
  <%= @toolbox.url %>
</p>

<!--
<p>
  <b>Type:</b>
  <%= @toolbox.type %>
</p>
-->
<p>
  <b>Developers:</b>
  <% [@toolbox.users[0]].each do |user| %>
        <%= link_to user.name, user %> 
  <% end %>
  </p>

  <h2> Tools </h2>

<% @toolbox.tools.each do |tool| %>
   <hr>
<div class='bit '>
<div class=''>


 <div class='title'>
 <%= link_to tool.name, tool %> 
 
 <%= link_to "Remove From Toolbox", tool_remove_from_favorites_path(tool.id), :class => 'add_label' %>


    <div class='tags'>
      <% tool.tag_list.each do |tag| %>
          <%= link_to tag, tool_filter_by_tag_path(tag), :class => 'label label-info tag' %> 


      <% end %>
    </div> <!--tags-->
 </div> <!--title-->
 </div> <!--row-->
</div> <!--bit row-->


<% end %>


<br/>
<br/>
<br/>

<%= link_to 'Edit', edit_toolbox_path(@toolbox) %> |
<%= link_to 'Go To All Toolboxes', toolboxes_path %>