config/routes.rb
CtoToolbox::Application.routes.draw do

  resources :toolboxes

  root :to => "static_pages#home"

  get "static_pages/home"

  get "user/list"
  get "user/disable"

  match 'users/:id/set_current_user' => 'users#set_current_user', :as => 'user_set_current_user', :via => "get"
  match 'tools/tag/:tag_name' => 'tools#filter_by_tag', :as => 'tool_filter_by_tag', :via => "get"
  match 'tools/:id/favorites' => 'tools#add_to_favorites', :as => 'tool_add_to_favorites', :via => "get" #TODO: change to post, and possibly change for this to be off /users endpoint
  match 'tools/:id/favorites' => 'tools#remove_from_favorites', :as => 'tool_remove_from_favorites', :via => "delete" #TODO: change to post, and possibly change for this to be off /users endpoint

  match "/auth/twitter/callback" => "sessions#create"

  
  resources :users
  resources :tags

  resources :tools
  resources :toolboxes
  match 'tools_search' => 'Tools#search_by_name', :as => :tools_search_by_name, :via => "get"
  match 'mytools' => 'Tools#my_tools', :as => :my_tools, :via => "get"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">CTO Toolbox</a>
    by <a href="http://linkedin.com/in/jbarmash">Jean Barmash </a>
  </small>
  <nav>
    <ul>
      <li><a href="mailto://jean.barmash@gmail.com">Email</a></li>
      <li><a href="http://www.hellofoobar.com/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "CTO Toolbox", root_path, id: "logo" %>
          <nav>
	  <ul class="nav pull-right">
	        <%# link_to "Sign in with Twitter", "/auth/t" %>
	        <li><%= link_to "Tools",  tools_path %></li>
            <li><%= link_to "My Tools",  my_tools_path %></li>
            <li><%= link_to "Toolboxes",  toolboxes_path %></li>
            <% if session[:current_toolbox] 
                current_toolbox = Toolbox.find(session[:current_toolbox])
            %>
            <li><%=link_to "TB: (#{current_toolbox.name})", toolbox_path(current_toolbox) %></li>
            <% end %>

            <li><%= link_to "Tags",    tags_path %></li>
            <li><%= link_to "Users",    users_path %></li>
              <% if session[:current_user] 
                 current_user = User.find(session[:current_user])
              %>
                  <li>  <%=link_to "Current User: #{current_user.name}", user_path(current_user) %></li>
              <% else %>
                  <li><%= link_to "Sign in (In Progress)", '#' %></li>
              <% end %>

            </ul>
          </nav>
        </div>
      </div>
      </header>

<% if flash[:notice] %>
    <div class="alert alert-info">
   <%= flash[:notice]%>
    </div>
<%  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CTO Toolbox</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%- #javascript_include_tag "application" -%>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
	  <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>